### ISSUE TITLE
Doc: bad link

### ISSUE THREAD

**Issue by DavidPhillipOster** [ploopyco/headphones#1]
The link "When you're ready, continue to Part 5: Cables and Conclusion at the bottom of https://github.com/ploopyco/headphones/wiki/Part-4%3A-Headband should go to https://github.com/ploopyco/headphones/wiki/Part-5%3A-Amplifier%2C-Cables-and-Conclusion but instead it goes to https://github.com/ploopyco/headphones/wiki/

**Comment by ploopyco** [comment]
Thanks for pointing this out!
