### ISSUE TITLE
Headband Sliders In Kit Different From Wiki

### ISSUE THREAD

**Issue by maxcaplan** [ploopyco/headphones#22]
The 3d printed headband slider pieces that came with my kit are different from the ones pictured in the assembly wiki on Github. I don't understand how the driver holders can be inserted into the headband sliders with the metal pins.

Images to show differences between the pieces: [https://imgur.com/a/lO0dYWh](https://imgur.com/a/lO0dYWh)

**Comment by ploopyco** [comment]
I believe we already talked elsewhere; if not, please contact us at contact@ploopy.co

For others' future reference, we don't monitor Github issues regularly. For product support, please use email (see above).
