### ISSUE TITLE
Ready to manufacture gbr files

### ISSUE THREAD

**Issue by onidev** [ploopyco/headphones#26]
Hello,

It is possible to release ready to manufacture files for pcbway/jlcpcb?
I don't have Altium and was not able to use/import files from here: https://github.com/ploopyco/headphones/issues/4

I assume they expect .gbr / .dlr files. For reference, I was able to make this PCB with jlcpcb:
https://github.com/Redherring32/OpenTendo
The release is ready to manufacture, and there are clear instructions on the main page (recommended PCB specs).

Thank you

**Comment by ploopyco** [comment]
Unfortunately, we can't act as the interface between you and your board house.
