### ISSUE TITLE
wireless support

### ISSUE THREAD

**Issue by RustoMCSpit** [ploopyco/headphones#29]

**Comment by RustoMCSpit** [comment]
wait as in, it works or out of scope?!?!

**Comment by RustoMCSpit** [comment]
bluetooth 5.3?

**Comment by shodanx2** [comment]
Hi,
I want to add wireless support, 
I think I will use a raspberry pi and stream real time audio over wifi to make the first, pure wifi wireless headphones with IP audio support. 
I"m trying to find a forum where anyone else ever attempted this. 
But this discussion is the only place I could find someone mentioning ploopy headphones and wireless.
