### ISSUE TITLE
GitHub Organization?

### ISSUE THREAD

**Issue by PhoneDroid** [ploopyco/headphones#31]
I was wondering if there was a reason you haven't converted  
the `ploopyco` GitHub account to a GitHub organization yet?

( Settings > Organization > Transform account )

I would also recommend enabling discussions on the organization, so  
there is a central place to discuss general ploopy topics on GitHub.

**Comment by PhoneDroid** [comment]
Also, is there a way to contribute fixes to the store page?

https://ploopy.co/shop/headphones-full-kit-preorder/?attribute_plastic-colour=Black&attribute_usb-a-to-usb-c-cable=Include+a+USB-A+to+USB-C+Cable

![image](https://github.com/ploopyco/headphones/assets/73050054/8aa97849-37e2-49dd-a838-5fefa9c790a2)

**Comment by PhoneDroid** [comment]
Also, also, since there is not discussions tab yet ( GitHub Organization ),
I will just add it here:

Will there be more colors in the future ( for the printed Headphone parts ) ?

**Comment by ploopyco** [comment]
Thanks for catching the typo. :) 

To keep the number of communications channels manageable, we're on Reddit (r/ploopy) and Discord (https://discord.gg/eYXvtpWBpn). Product support goes through email at contact@ploopy.co.
