### ISSUE TITLE
Headphones disconnecting

### ISSUE THREAD

**Issue by doomguy-47** [ploopyco/headphones#32]
Occasionally my headphones will not output any sound and you can't change the volume. It won't move when you press the buttons and if you use the slider it will just go back once you close the window.  Youtube displays an error saying that the audio drivers are invalid or something like that. 

It is fixed by temporarily unplugging the DAC and plugging it back in and with a windows restart.

I've already updated windows and checked drivers in device manager and it hasn't fixed it. My DAC is double sided taped to the bottom of my desk but does not feel hot. It might be caused from launching a game but I'm not sure since I turn on a game after my computer has been on for a while.

I've look at another issue linked [here ](https://github.com/ploopyco/headphones/issues/20) about some ones headphones not working after a section in a song but I could not repeat it. My DAC is double sided taped to the bottom of my desk but does not feel too hot.

**Comment by ploopyco** [comment]
We're finding that the DAC draws too much power for some USB ports, which can result in the upstream host cutting power. The best thing to do in this case is 1) turn the volume down or 2) find a port with a higher power capability (powered hubs tend to be pretty good bets in this regard).

If you need further support, please email contact@ploopy.co
