### ISSUE TITLE
unmerge 3d files

### ISSUE THREAD

**Issue by sirus20x6** [ploopyco/headphones#5]
It would really be helpful if every 3d part was in its own file. I'm not sure what we're supposed to do with them all merged together, but I can't give this to my 3d printer

**Comment by sirus20x6** [comment]
Been poking at this for a while now. even in the step file everything is fused into one object. you can't actually 3d print it this way.

**Comment by ploopyco** [comment]
Cura and PrusaSlicer are two free tools that have both been tested and verified as having the ability to "split" the file into the individual pieces.

As for the STEP file, FreeCAD and Blender are also two free tools that have been tested and verified as having the ability to split the file into the individual components for modification.

**Comment by sirus20x6** [comment]
I was unable to split them in either freecad or blender

**Comment by sirus20x6** [comment]
I just tried cura. it is unable to split the stl because all the geometry is together under one object. cura is unable to load the stp file

**Comment by sirus20x6** [comment]
I just tried prusa slicer as well. it was able to load the stp file, but all the geometry again was under one single object which means it cant be split. it has to be printed as is. in order to print any of these they have to each be their own object which can be done with stp, but is not in this step file.
